# অধ্যায় ৩ঃ ডেটা বিশ্লেষণ (বর্ননামূলক পরিসংখ্যানের মাধ্যমে ডেটার সম্পর্কে জানা)

গত দুই অধ্যায়ে আমরা মেশিন লার্নিং মডেল তৈরির ধাপসমূহের সম্পর্কে জেনেছি এবং টুকটাক পরিসংখ্যান সম্পর্কে জেনেছি। এই অধ্যায়
থেকে আমরা মেশিন লার্নিং প্রেডিক্টিভ মডেল তৈরির ধাপসমূহ সম্পর্কে বিস্তারিত জানব। এই অধ্যায় শেষে যা যা শিখব।

১) কিভাবে ডেটাসেট লোড করতে হয়। 

২) কিভাবে ডেটাসেট থেকে ডেটা দেখতে হয় । 

৩) কিভাবে ডেটাসেটের ডাইমেনশন সম্পর্কে জানা যায় । 

৪) কিভাব ফিচারগুলোর ডেটাটাইপ সম্পর্কে জানা যায় । 

৫) কিভাব বর্ননামূলক পরিসংখ্যানের মাধ্যমে ডেটার সম্পর্কে জানা যায় । 

৬) কিভাব ক্লাস ডিস্ট্রিবিউশন সম্পর্কে জানা যায় । 

৭) কিভাব ফিচারগুলোর মধ্যকার সম্পর্ক (Correlation)যায় । 

৮) কিভাব এট্রিবিউটগুলো skew সম্পর্কে জানা যায় । 


## ৩.১ বর্ননামূলক পরিসংখ্যানের মাধ্যমে ডেটার সম্পর্কে জানা 

Descriptive statistics হচ্ছে ডেটাসেটের ভ্যারিয়েবলগুলোকে বর্ননা বা ব্যাখ্যা করার পদ্বতি। অর্থাৎ যার মাধ্যমে ডেটাসেটের সম্পর্কে সার্বিক ধারনা পাওয়া যায়। মেশিনকে শেখানোর আগে ডেটা সম্পর্কে পর্যাপ্ত জ্ঞান থাকা প্রয়োজন। কেননা ডেটাসেটকে কোন কোন পদ্বতিতে পরিবর্তন করে মেশিন লার্নিং এলগোরিদমের জন্য তৈরি করতে হবে তা এই ধাপে সিদ্বান্ত নিতে হবে। 

### ৩.১.১ ডেটাসেট লোড করা 
ডেটসেট লোড করার সময় মনে রাখতে হবে আমাদের যে ফোল্ডারে জুপিটার ফাইলটি SAVE করে রাখব সেই ফোল্ডারে csv ফাইলটি রাখতে হবে।

প্রথমে দরকারি লাইব্রেরিগুলো লোড করে নিতে হবে। পাইথনে ডেটা ম্যানিপুলেশনের জন্য চমৎকার লাইব্রেরি হচ্ছে pandas। আমরা pandas এর read_csv() ফাংশনের মাধ্যমে ডেটা লোড করব এবং পরবর্তিতে pandas এর চমৎকার মেথড ও এট্রিবিউট ব্যবহার করব। 

In [2]:
# Import libraries
import pandas as pd
import numpy as np

In [6]:
# load dataset
dataset = pd.read_csv('diabetes.csv')

### ৩.১.২ ডেটাসেট থেকে ডেটা দেখা 
লোড করা ডেটাসেট থেকে ডেটা দেখা এবং ডেটা সম্পর্কে ধারনা নিতে হবে । যেমনঃ কি কি ফিচার রয়েছে??, ফিচারগুলোর ভ্যালুগুলো কি একই স্কেলে আছে নাকি ভিন্ন ভিন্ন স্কেলে আছে। যদি ভিন্ন ভিন্ন স্কেলে থাকে তাহলে ডেটা প্রিপ্রসেসিং ধাপে তাদেরকে রিস্কেল করে একই স্কেলে আনতে হবে। এতে করে মেশিন ভালোভাবে শিখতে পারে। 
ডেটাসেট থেকে ডেটা দেখার জন্য pandas dataframe এর head() ফাংশনটি ব্যবহার করব। 

In [7]:
dataset.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

আমরা এখানে দেখতে পাচ্ছি ডেটাগুলো বিভিন্ন স্কেলের রয়েছে। এই ডেটাগুলোকে ডেটা প্রিপ্রসেসিং এর রিস্কেল টেকনিক ব্যবহার করে একই স্কেলে আনতে হবে। 

### ৩.১.৩ ডেটাসেটের  ডাইমেনশন সম্পর্কে জানা 
ডেটাসেটের  ডাইমেনশন বলতে ডেটাসেটটিতে কয়টি ফিচার এবং কয়টি অবজারভেশন রয়েছে তা বুঝায়। ডেটাসেটের ডাইমেশন সম্পর্কে  জানা খুবই জরুরী কারণ - 

১) ডেটাসেটে  অবজারভেশন অর্থাৎ সারি  যদি  কম থাকে তাহলে মেশিন ঠিকঠাকমত শিখতে পারবে না।যত বেশি ডেটা তত বেশি জ্ঞান।  আবার যদি অবজারভেশন অনেক বেশি থাকে তাহলে মেশিনকে ট্রেইন করাতে অনেক সময় লাগবে। 

২) ডেটাসেটে যদি অনেকবেশি ফিচার থাকে অর্থাৎ কলাম  থাকে তাহলে মেশিন ভালোভাবে শিখতে পারবে না। কারণ এর মধ্যে অনেক ফিচার থাকে যা মেশিনকে ডেটাগুলোর মধ্যে সম্পর্ক তৈরি করতে কনফিউজ করে দেয়। এক্ষেত্রে ডেটা প্রিপ্রসেসিং এ ফিচার সিলেকশন টেকনিক ব্যবহার করে গুরুত্বপূর্ন ফিচার সিলেকশনের মাধ্যমে ফিচারের সংখ্যা কমিয়ে আনতে হবে।   

In [9]:
# Dimensions of your data
dataset.shape

(768, 9)

আমরা দেখতে পাচ্ছি ডেটাসেটির ৭৬৮ টি অবজারভেশন এবং ৯ টি ফিচার রয়েছে। মেশিনকে শেখানোর জন্য ডেটাসেটটি মোটামুটি উপযোগী। 

### ৩.১.৪ ফিচারগুলোর ডেটাটাইপ সম্পর্কে জানা 
প্রতিটা ফিচারের ডেটা টাইপ সম্পর্কে জানা প্রযোজন কেননা কোন ফিচারের ডেটাটাইপ যদি স্ট্রিং হয় তাহলে মেশিন তা থেকে শিখতে পারবে।
কারণ মেশিন শুধুমাত্র সংখ্যা চেনে। তাই ডেটাটাইপ স্ট্রিং হলে তাকে ডেটা প্রিপ্রসেসিং টেকনিক ব্যবহার করে সংখ্যায় পরির্তন করে নিতে হবে। 

In [11]:
# Data Types for Each Attribute
types = dataset.dtypes
print(types)

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object


এখানে বেশিরভাগ ফিচারের ডেটা টাইপ integer এবং float। কোন স্ট্রিং ডেটাটাইপ নেই। 

### ৩.১.৫ বর্ননামূলক পরিসংখ্যানের মাধ্যমে ডেটার সম্পর্কে জানা

বর্ননামূলক পরিসংখ্যানের(Descriptive statistics) মাধ্যমে ডেটার ভেতরকার খবর দ্রুত এবং ভালোভাবে জানা যায়। pandas এর describe() ফাংশনের মাধ্যমে প্রতিটি ফিচারের ৮ টি statistical properties দেখা যায়। 

১) count ২) Mean ৩) Standard deviation ৪) Minimum value ৫) 25th percentile ৬) 50th percentile ৭) 75th percentile ৮) Maximum value

In [12]:
# Descriptive statistics
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

count দ্বারা আমরা জানতে পারি কতগুলো অবজারভেশন রয়েছে ঐ ফিচারের। এর মাধ্যমে কোন ফিচারের ডেটা মিসিং আছে কি না জানা যায়। ডেটা মিসিং থাকলে তা ডেটা প্রিপ্রসেসিং টেকনিকের মাধ্যমে তা হ্যান্ডেল করতে হবে। 
আমরা দেখতে পাচ্ছি এখানে কোন ফিচারের ডেটা মিসিং নেই। 

Mean হচ্ছে ঐ ফিচারের গড় ভ্যালু। যা ঐ ফিচারের ডেটার প্রতিনিধিত্ব করে।

std হচ্ছে standard deviation যার মাধ্যমে আমরা ডেটার ভ্যারিয়েশন জানতে পারি। std বেশি হলে বুঝতে হবে ঐ ফিচারের ভ্যালুগুলোর বিস্তার অর্থাৎ একটি ভ্যালুর থেকে আরেকটি ভ্যালুর দূরত্ব বেশি।  এক্ষেত্রে ডেটা প্রসেসিং টেকনিক ব্যবহার করে ব্যপারটি হ্যান্ডেল করতে হবে। std এর মানে -3<std<3 এর মধ্যে হলে ভালো। 

min এবং max এর ফিচারের ভ্যালুর সবচেয়ে ছোট এবং সবেচেয়ে বেশি মান নির্দেশ করে। এর মাধ্যমে ডেটার রেঞ্জ সম্পর্কে ধারনা পাওয়া যায়। 

25%, 50%, 75% এর মাধ্যমে জানা যায় ভ্যালুগুলো এর নিচে অবস্থান করছে। যেমন  আমাদের ডেটাসেটের Pregnancies ফিচারের 25% ভ্যালু 1.000000 এর নিচে অবস্থান করছে। 

তাহলে আমরা Descriptive statistics এর মাধ্যমে ডেটা সম্পর্কে গভীর ধারনা পাই এবং কোন কোন ফিচারকে প্রিপ্রসেসিং করতে হবে  সেই সিদ্বান্ত নেওয়া যায়। 

## ৩.১.৬ ক্লাস ডিস্ট্রিবিউশন সম্পর্কে জানা 


ক্লাসিফিকেশন সমস্যায় আমাদের লেভেল ডেটা হিসেবে হ্যাঁ অথবা না থাকে অর্থাৎ 0 অথবা 1 থাকে (মাল্টিপল ক্লাসিফিকেশন প্রবলেম এ ক্ষেত্রে 0, 1, 2 থাকে)। ক্লাস ডিস্ট্রিবিউশন হচ্ছে আমাদের ডেটা সেটে কয়টি 0 এবং 1 আছে সে তা জানা । এটি জানা জরুরী কেননা যদি ক্লাস ডিস্ট্রিবিউশনে যদি অনেক বেশি পার্থক্য থাকে তাহলে তা মেশিনকে শেখানোর সময় খারাপ প্রভাব ফেলতে পারে। সেক্ষেত্রে ডেটা প্রিপ্রসেসিং এর সময়  স্পেশাল টেকনিকের মাধ্যমে ডেটাকে হ্যান্ডেল করতে হবে। 

In [14]:
class_counts = dataset.groupby('Outcome').size()
print(class_counts)

Outcome
0    500
1    268
dtype: int64


আমরা এখানে দেখতে পাচ্ছি 0 ক্লাসে অবজারভেশন 1 ক্লাসের অবজারভেশনের প্রায় দ্বিগুণ 

## ৩.১.৬ ফিচারগুলোর মধ্যকার সম্পর্ক (Correlation)

কোরিলেশন হচ্ছে একটি ভ্যারিয়েবলের পরিবর্তনের ফলে আরেকটি ভ্যালু কিরূপ পরিবতর্ন হয় । এই সম্পর্কে অধ্যায় দুইইয়ে বিস্তারিত আলোচনা করা হয়েছে। 
ফিচারগুলোর মধ্যে কোরিলেশন জানা জরুরী কেননা ভ্যারিয়েবলগুলোর মধ্যে যদি highly correlation থাকে তাহলে কিছু  কিছু মেশিন লার্নিং এলগোরিদম (linear & Logistic regression) আছে  যেগুলো ডেটা থেকে ভালো ভালো শিখতে পারে না। 

In [16]:
dataset.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

 আমরা এখানে দেখতে পাচ্ছি ডেটাগুলো নিজেদের সাথে ছাড়া অন্য কোন এট্রিবিউটের সাথে Highly correlation নাই। যদি অন্য কোন ফিচারের সাথে  -0.8 থেকে -1.0 থাকত তাহলে তাকে Negative highly correlation বলা হত । অথবা 8.0 থেকে 1.0 হত তাহলে Positive highly correlation বলা হত। 

## ৩.১.৭  এট্রিবিউটগুলো skew সম্পর্কে জানা 

নরমাল বা গসিয়ান ডিস্ট্রিবিউশনের কিছুটা পরিবর্তনই হচ্ছে skew। অনেক মেশিন লার্নিং এলগরিদম আছে যেগুলো ডেটার নরমাল ডিস্ট্রিবিউশন থেকে ডেটা সম্পর্কে ভালোভাবে শিখতে পারে। তাই Skew সম্পর্কে জেনে ডেটা প্রিপ্রসেসিং টেকনিক ব্যবহার করে তাদেরকে নরমাল ডিস্ট্রিবিউশনে পরিবর্তন করতে হবে এতে করে মেশিন লার্নিং মডেলের পারফর্মেন্স ভালো হবে। 

In [17]:
dataset.skew()

Pregnancies                 0.901674
Glucose                     0.173754
BloodPressure              -1.843608
SkinThickness               0.109372
Insulin                     2.272251
BMI                        -0.428982
DiabetesPedigreeFunction    1.919911
Age                         1.129597
Outcome                     0.635017
dtype: float64

skew এর ভ্যালু যদি পজিটিভ হয় তাহলে তাকে পজেটিভ skew বলে অর্থাৎ ডেটার কেন্দ্রীয় মান ডেটা ডান দিকে বেশি বিস্তৃত। আবার যদি skew এর ভ্যালু যদি নেগেটিভ  হয় তাহলে তাকে নেগেটিভ skew বলে অর্থাৎ ডেটার কেন্দ্রীয় মান ডেটা বাম দিকে বেশি বিস্তৃত।
skew এর ভ্যালু যদি ০ এর কাছাকাছি হয় তাহলে সেই ফিচারের ডেটাগুলো নরমাল ডিস্ট্রিবিউশনের এর কাছাকাছি। যা থেকে মেশিন ভালোভাবে শিখতে পারে। 

# ৩.২ ডেটা বিশ্লেষণের মাধ্যমে ডেটাকে নিয়ে যে যে  সিদ্বান্ত নিলাম 

১) ডেটাগুলো বিভিন্ন স্কেলে রয়েছে এগুলোকে Rescale করে একটি নির্দিস্ট স্কেলে আনতে হবে। 

২) বেশিরভাগ ফিচারের std অনেক বেশি তাই ডেটাগুলোকে Standardize করতে হবে। 

৩) ক্লাস ডিস্টিবিউশনের পার্থক্য বেশি এক্ষেত্রে ডেটাকে সাবধানতার সাথে স্প্লিট করতে হবে। 

৪) কিছু কিছু এট্রিবিউট নরমাল ডিস্ট্রিবিউশনের কাছাকাছি এই ফিচারগুলোকে Normalize করতে হবে। 

ইনশাআল্লাহ আমরা ডেটা প্রিপ্রসেসিং টেকনিক অধ্যায় ৫ এ শিখব। 


## ৩.৩  কিছু টিপস 

Descriptive statistics ব্যবহারের মাধ্যমে ডেটা সম্পর্কে জানার সময় কিছু জিনিস মনে রাখতে হবে। 

১) বিভিন্ন ফিচারের Descriptive statistics এর ভ্যালুগুলোকে  নিয়ে চিন্তা করতে হবে ।

২) প্রশ্ন করতে হবে ভ্যালুগুলো এমন আসছে কেন? ভ্যালুগুলো এমন আসার কারণ কি? এই ভ্যালুগুলো আমাদের ডোমেনের প্রবলেমের সাথে কিভাবে জড়িত। 

৩) ডেটা থেকে প্রাপ্ত জ্ঞান এবং ডেটাগুলোর কি কি পরিবর্তন আনতে হবে তা লিখে রাখা। পরবর্তিতে ডেটা প্রেসেসিং এ সে অনুযায়ী কাজ করতে হবে। 

# ৩.৪ এই অধ্যায় থেকে যা যা শিখলাম 
ডেটা বিশ্লেষণের মাধ্যমে ডেটার ভেতরকার খবর জানলাম এবং ডেটার মধ্যে কি কি পরিবর্তন আনতে হবে তা জানলাম। কিছু টেকনিকের মাধ্যমে -- 

১) ডেটাসেট লোড করা

২) ডেটাসেট থেকে ডেটা দেখা। 

৩) ডেটাসেটের ডাইমেনশন সম্পর্কে জানা। 

৪) ফিচারগুলোর ডেটাটাইপ সম্পর্কে জানা। 

৫) বর্ননামূলক পরিসংখ্যানের মাধ্যমে ডেটার সম্পর্কে জানা। 

৬) ক্লাস ডিস্ট্রিবিউশন সম্পর্কে জানা। 

৭) ফিচারগুলোর মধ্যকার সম্পর্ক (Correlation)। 

৮) এট্রিবিউটগুলো skew সম্পর্কে জানা। 


# ৩.৫ পরের অধ্যায়ে যা শিখব 

ডেটা সম্পর্কে আরো ভালোভাবে জানার পদ্বতি হচ্ছে ডেটা ভিজুয়ালাইজেশন।  ডেটা ভেতরকার খবর ভালোভাবে জানার জন্য ডেটা ভিজুয়ালাইজেশনের জুরি নেই। পরের অধ্যায়ে কিভাবে ডেটা ভিজুয়ালাইজেশনের মাধ্যমে ডেটা থেকে জ্ঞান নেওয়া যায় তা জানব। ইনশাআল্লাহ। 